/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as DataRouteImport } from './routes/data'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HostRouteImport } from './routes/host'
import { Route as LaddersRouteImport } from './routes/ladders'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as MuseRouteImport } from './routes/muse'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as StackRouteImport } from './routes/stack'
import { Route as WorksRouteImport } from './routes/works'
import { Route as LabLabIdRouteImport } from './routes/lab.$labId'
import { Route as PathsSlugRouteImport } from './routes/paths.$slug'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LaddersRoute = LaddersRouteImport.update({
  id: '/ladders',
  path: '/ladders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseRoute = MuseRouteImport.update({
  id: '/muse',
  path: '/muse',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLabIdRoute = LabLabIdRouteImport.update({
  id: '/lab/$labId',
  path: '/lab/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PathsRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/audit': typeof AuditRoute
  '/baseline': typeof BaselineRoute
  '/canon': typeof CanonRoute
  '/data': typeof DataRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/manuals': typeof ManualsRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/school': typeof SchoolRoute
  '/stack': typeof StackRoute
  '/works': typeof WorksRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/audit': typeof AuditRoute
  '/baseline': typeof BaselineRoute
  '/canon': typeof CanonRoute
  '/data': typeof DataRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/manuals': typeof ManualsRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/school': typeof SchoolRoute
  '/stack': typeof StackRoute
  '/works': typeof WorksRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/audit': typeof AuditRoute
  '/baseline': typeof BaselineRoute
  '/canon': typeof CanonRoute
  '/data': typeof DataRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/manuals': typeof ManualsRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/school': typeof SchoolRoute
  '/stack': typeof StackRoute
  '/works': typeof WorksRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/audit'
    | '/baseline'
    | '/canon'
    | '/data'
    | '/desk'
    | '/editor'
    | '/host'
    | '/ladders'
    | '/manuals'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/school'
    | '/stack'
    | '/works'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/audit'
    | '/baseline'
    | '/canon'
    | '/data'
    | '/desk'
    | '/editor'
    | '/host'
    | '/ladders'
    | '/manuals'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/school'
    | '/stack'
    | '/works'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/audit'
    | '/baseline'
    | '/canon'
    | '/data'
    | '/desk'
    | '/editor'
    | '/host'
    | '/ladders'
    | '/manuals'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/school'
    | '/stack'
    | '/works'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuditRoute: typeof AuditRoute
  BaselineRoute: typeof BaselineRoute
  CanonRoute: typeof CanonRoute
  DataRoute: typeof DataRoute
  DeskRoute: typeof DeskRoute
  EditorRoute: typeof EditorRoute
  HostRoute: typeof HostRoute
  LaddersRoute: typeof LaddersRoute
  ManualsRoute: typeof ManualsRoute
  MuseRoute: typeof MuseRoute
  PathsRoute: typeof PathsRouteWithChildren
  RadarRoute: typeof RadarRoute
  SchoolRoute: typeof SchoolRoute
  StackRoute: typeof StackRoute
  WorksRoute: typeof WorksRoute
  LabLabIdRoute: typeof LabLabIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladders': {
      id: '/ladders'
      path: '/ladders'
      fullPath: '/ladders'
      preLoaderRoute: typeof LaddersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muse': {
      id: '/muse'
      path: '/muse'
      fullPath: '/muse'
      preLoaderRoute: typeof MuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$labId': {
      id: '/lab/$labId'
      path: '/lab/$labId'
      fullPath: '/lab/$labId'
      preLoaderRoute: typeof LabLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof PathsRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PathsRouteChildren {
  PathsSlugRoute: typeof PathsSlugRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsSlugRoute: PathsSlugRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuditRoute: AuditRoute,
  BaselineRoute: BaselineRoute,
  CanonRoute: CanonRoute,
  DataRoute: DataRoute,
  DeskRoute: DeskRoute,
  EditorRoute: EditorRoute,
  HostRoute: HostRoute,
  LaddersRoute: LaddersRoute,
  ManualsRoute: ManualsRoute,
  MuseRoute: MuseRoute,
  PathsRoute: PathsRouteWithChildren,
  RadarRoute: RadarRoute,
  SchoolRoute: SchoolRoute,
  StackRoute: StackRoute,
  WorksRoute: WorksRoute,
  LabLabIdRoute: LabLabIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
