/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as HostRouteImport } from './routes/host'
import { Route as LaddersRouteImport } from './routes/ladders'
import { Route as MuseRouteImport } from './routes/muse'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as StackRouteImport } from './routes/stack'
import { Route as LabLabIdRouteImport } from './routes/lab.$labId'
import { Route as PathsSlugRouteImport } from './routes/paths.$slug'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LaddersRoute = LaddersRouteImport.update({
  id: '/ladders',
  path: '/ladders',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseRoute = MuseRouteImport.update({
  id: '/muse',
  path: '/muse',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLabIdRoute = LabLabIdRouteImport.update({
  id: '/lab/$labId',
  path: '/lab/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PathsRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/desk': typeof DeskRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/stack': typeof StackRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/desk': typeof DeskRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/stack': typeof StackRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/desk': typeof DeskRoute
  '/host': typeof HostRoute
  '/ladders': typeof LaddersRoute
  '/muse': typeof MuseRoute
  '/paths': typeof PathsRouteWithChildren
  '/radar': typeof RadarRoute
  '/stack': typeof StackRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canon'
    | '/desk'
    | '/host'
    | '/ladders'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/stack'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canon'
    | '/desk'
    | '/host'
    | '/ladders'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/stack'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/canon'
    | '/desk'
    | '/host'
    | '/ladders'
    | '/muse'
    | '/paths'
    | '/radar'
    | '/stack'
    | '/lab/$labId'
    | '/paths/$slug'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanonRoute: typeof CanonRoute
  DeskRoute: typeof DeskRoute
  HostRoute: typeof HostRoute
  LaddersRoute: typeof LaddersRoute
  MuseRoute: typeof MuseRoute
  PathsRoute: typeof PathsRouteWithChildren
  RadarRoute: typeof RadarRoute
  StackRoute: typeof StackRoute
  LabLabIdRoute: typeof LabLabIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladders': {
      id: '/ladders'
      path: '/ladders'
      fullPath: '/ladders'
      preLoaderRoute: typeof LaddersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muse': {
      id: '/muse'
      path: '/muse'
      fullPath: '/muse'
      preLoaderRoute: typeof MuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$labId': {
      id: '/lab/$labId'
      path: '/lab/$labId'
      fullPath: '/lab/$labId'
      preLoaderRoute: typeof LabLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof PathsRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PathsRouteChildren {
  PathsSlugRoute: typeof PathsSlugRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsSlugRoute: PathsSlugRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanonRoute: CanonRoute,
  DeskRoute: DeskRoute,
  HostRoute: HostRoute,
  LaddersRoute: LaddersRoute,
  MuseRoute: MuseRoute,
  PathsRoute: PathsRouteWithChildren,
  RadarRoute: RadarRoute,
  StackRoute: StackRoute,
  LabLabIdRoute: LabLabIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
