export type CanonDomain =
  | "mathematics"
  | "physics"
  | "chemistry"
  | "life"
  | "computing"
  | "engineering"
  | "philosophy"
  | "hermetica"
  | "languages"
  | "certifications"
  | "practice";

export type CanonEntry = {
  id: string;
  domain: CanonDomain;
  title: string;
  source: string;
  href: string;
  license: string;
  implements: string;
};

export const canonDomains: { id: CanonDomain | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "mathematics", label: "Mathematics" },
  { id: "physics", label: "Physics" },
  { id: "chemistry", label: "Chemistry" },
  { id: "life", label: "Life" },
  { id: "computing", label: "Computing" },
  { id: "engineering", label: "Engineering" },
  { id: "philosophy", label: "Philosophy" },
  { id: "hermetica", label: "Hermetica" },
  { id: "languages", label: "Languages" },
  { id: "certifications", label: "Certifications" },
  { id: "practice", label: "Practice" },
];

export const canon: CanonEntry[] = [
  {
    id: "openstax-calc",
    domain: "mathematics",
    title: "Calculus, Volumes 1–3",
    source: "OpenStax",
    href: "https://openstax.org/details/books/calculus-volume-1",
    license: "CC BY-NC-SA",
    implements: "Reading for the ops-math path. We do not reprint the book.",
  },
  {
    id: "openstax-stats",
    domain: "mathematics",
    title: "Introductory Statistics 2e",
    source: "OpenStax",
    href: "https://openstax.org/details/books/introductory-statistics-2e",
    license: "CC BY",
    implements: "The hold-out and base-rate language on the detection benches.",
  },
  {
    id: "dlmf",
    domain: "mathematics",
    title: "Digital Library of Mathematical Functions",
    source: "NIST",
    href: "https://dlmf.nist.gov/",
    license: "NIST public",
    implements: "Lookup, not a solver. Cited when a lab needs a named function.",
  },
  {
    id: "oeis",
    domain: "mathematics",
    title: "On-Line Encyclopedia of Integer Sequences",
    source: "OEIS Foundation",
    href: "https://oeis.org/",
    license: "OEIS terms",
    implements: "A check against invented sequences in drills.",
  },
  {
    id: "euclid",
    domain: "mathematics",
    title: "The Thirteen Books of Euclid's Elements",
    source: "Project Gutenberg, Heath translation",
    href: "https://www.gutenberg.org/ebooks/21076",
    license: "Public domain",
    implements: "Primary text for proof discipline. Not a modern axiom system.",
  },
  {
    id: "mit-1806",
    domain: "mathematics",
    title: "Linear Algebra (18.06)",
    source: "MIT OpenCourseWare",
    href: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/",
    license: "CC BY-NC-SA",
    implements: "The matrix picture behind feature tables on the benches.",
  },
  {
    id: "openstax-phys",
    domain: "physics",
    title: "University Physics, Volume 1",
    source: "OpenStax",
    href: "https://openstax.org/details/books/university-physics-volume-1",
    license: "CC BY",
    implements: "Mechanics reference. The 3D stage is a mark, not a physics engine.",
  },
  {
    id: "nist-constants",
    domain: "physics",
    title: "CODATA fundamental constants",
    source: "NIST",
    href: "https://physics.nist.gov/cuu/Constants/index.html",
    license: "NIST public",
    implements: "Numbers come from here. We do not round them into lore.",
  },
  {
    id: "phet",
    domain: "physics",
    title: "PhET interactive simulations",
    source: "University of Colorado",
    href: "https://phet.colorado.edu/",
    license: "CC BY",
    implements: "External sims. Our stage does not replace them.",
  },
  {
    id: "arxiv",
    domain: "physics",
    title: "arXiv",
    source: "Cornell University",
    href: "https://arxiv.org/",
    license: "Author-posted, various",
    implements: "Frontier path: a paper is a signal, not a curriculum, until a path claims it.",
  },
  {
    id: "openstax-chem",
    domain: "chemistry",
    title: "Chemistry 2e",
    source: "OpenStax",
    href: "https://openstax.org/details/books/chemistry-2e",
    license: "CC BY",
    implements: "General chemistry shelf. No lab glassware is simulated here.",
  },
  {
    id: "webbook",
    domain: "chemistry",
    title: "Chemistry WebBook",
    source: "NIST",
    href: "https://webbook.nist.gov/chemistry/",
    license: "NIST public",
    implements: "Species data. We do not cache a private copy.",
  },
  {
    id: "pubchem",
    domain: "chemistry",
    title: "PubChem",
    source: "NCBI",
    href: "https://pubchem.ncbi.nlm.nih.gov/",
    license: "Public domain (US government)",
    implements: "Compound lookup. Not wired to a live query from this app.",
  },
  {
    id: "openstax-bio",
    domain: "life",
    title: "Biology 2e",
    source: "OpenStax",
    href: "https://openstax.org/details/books/biology-2e",
    license: "CC BY",
    implements: "The word interstitium is anatomical. The product name is a metaphor for gaps between systems.",
  },
  {
    id: "bookshelf",
    domain: "life",
    title: "NCBI Bookshelf",
    source: "National Library of Medicine",
    href: "https://www.ncbi.nlm.nih.gov/books/",
    license: "Per book",
    implements: "Primary biomedical texts. We do not mirror clinical guidance.",
  },
  {
    id: "uniprot",
    domain: "life",
    title: "UniProt",
    source: "UniProt Consortium",
    href: "https://www.uniprot.org/",
    license: "CC BY",
    implements: "Protein records. Out of the security benches on purpose.",
  },
  {
    id: "python",
    domain: "computing",
    title: "Python 3 documentation",
    source: "Python Software Foundation",
    href: "https://docs.python.org/3/",
    license: "PSF",
    implements: "The language of the malware benches and the stack page.",
  },
  {
    id: "rust",
    domain: "computing",
    title: "The Rust Programming Language",
    source: "Rust project",
    href: "https://doc.rust-lang.org/book/",
    license: "MIT OR Apache-2.0",
    implements: "Systems reading. No Rust toolchain runs in the browser.",
  },
  {
    id: "go",
    domain: "computing",
    title: "Go documentation",
    source: "Go project",
    href: "https://go.dev/doc/",
    license: "BSD-3",
    implements: "Service language on the platform path. Not executed here.",
  },
  {
    id: "mdn",
    domain: "computing",
    title: "MDN Web Docs",
    source: "Mozilla",
    href: "https://developer.mozilla.org/",
    license: "CC BY-SA",
    implements: "The browser surface this app is actually built with.",
  },
  {
    id: "k8s",
    domain: "computing",
    title: "Kubernetes documentation",
    source: "CNCF",
    href: "https://kubernetes.io/docs/",
    license: "CC BY",
    implements: "CKA and SRE paths. The cluster on the stage is a picture, not a kube-apiserver.",
  },
  {
    id: "podman",
    domain: "computing",
    title: "Podman documentation",
    source: "Containers project",
    href: "https://docs.podman.io/",
    license: "Apache-2.0",
    implements: "The container runtime named for the RHEL host, not Docker-only.",
  },
  {
    id: "terraform",
    domain: "computing",
    title: "Terraform documentation",
    source: "HashiCorp",
    href: "https://developer.hashicorp.com/terraform/docs",
    license: "MPL-2.0 for the CLI",
    implements: "IaC path. Plans are read. This app does not apply them.",
  },
  {
    id: "rhel-docs",
    domain: "computing",
    title: "RHEL 10 documentation",
    source: "Red Hat",
    href: "https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10",
    license: "Red Hat",
    implements: "The host runbook follows this, including the virtualization guide.",
  },
  {
    id: "man-pages",
    domain: "computing",
    title: "Linux man-pages",
    source: "man7.org",
    href: "https://man7.org/linux/man-pages/",
    license: "Various, mostly permissive",
    implements: "The desk parser is a toy. The man pages are the authority.",
  },
  {
    id: "owasp",
    domain: "computing",
    title: "OWASP Top 10",
    source: "OWASP Foundation",
    href: "https://owasp.org/www-project-top-ten/",
    license: "CC BY-SA",
    implements: "Frame for the security briefings. Not a scanner.",
  },
  {
    id: "nist-800",
    domain: "computing",
    title: "NIST Special Publications, 800 series",
    source: "NIST",
    href: "https://csrc.nist.gov/publications/sp800",
    license: "US public",
    implements: "Control language behind the detection capstone.",
  },
  {
    id: "attack",
    domain: "computing",
    title: "MITRE ATT&CK",
    source: "MITRE",
    href: "https://attack.mitre.org/",
    license: "Terms of use",
    implements: "Names for adversary behavior. We do not ship attack procedures.",
  },
  {
    id: "aac",
    domain: "engineering",
    title: "All About Circuits textbooks",
    source: "All About Circuits",
    href: "https://www.allaboutcircuits.com/textbook/",
    license: "Free to read, their terms",
    implements: "Circuits shelf for the engineering gap. No SPICE in this app.",
  },
  {
    id: "mit-6002",
    domain: "engineering",
    title: "Circuits and Electronics (6.002)",
    source: "MIT OpenCourseWare",
    href: "https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/",
    license: "CC BY-NC-SA",
    implements: "External course. Not reimplemented as a lab.",
  },
  {
    id: "sep",
    domain: "philosophy",
    title: "Stanford Encyclopedia of Philosophy",
    source: "Stanford University",
    href: "https://plato.stanford.edu/",
    license: "SEP citation policy",
    implements: "The reference before a primary text. Peer reviewed, revised.",
  },
  {
    id: "perseus",
    domain: "philosophy",
    title: "Internet Classics Archive",
    source: "MIT",
    href: "https://classics.mit.edu/",
    license: "Public-domain translations",
    implements: "Plato, Aristotle, and the rest in translation. Not a commentary.",
  },
  {
    id: "meditations",
    domain: "philosophy",
    title: "Meditations",
    source: "Project Gutenberg",
    href: "https://www.gutenberg.org/ebooks/2680",
    license: "Public domain",
    implements: "A primary text. Practice is still the benches, not a quote.",
  },
  {
    id: "discourse",
    domain: "philosophy",
    title: "Discourse on the Method",
    source: "Project Gutenberg",
    href: "https://www.gutenberg.org/ebooks/59",
    license: "Public domain",
    implements: "Method before mystique. Paired with the Hermetica shelf on purpose.",
  },
  {
    id: "republic",
    domain: "philosophy",
    title: "The Republic",
    source: "Project Gutenberg",
    href: "https://www.gutenberg.org/ebooks/1497",
    license: "Public domain",
    implements: "Primary text. The cave is not a model of this product.",
  },
  {
    id: "hermes",
    domain: "hermetica",
    title: "Thrice-Greatest Hermes",
    source: "G.R.S. Mead, 1906, sacred-texts archive",
    href: "https://archive.org/details/MeadGRSThriceGreatestHermesVolII1906",
    license: "Public domain, 1906",
    implements: "Historical Corpus Hermeticum. It is a text, not a claim about hidden physics.",
  },
  {
    id: "monas",
    domain: "hermetica",
    title: "Monas Hieroglyphica",
    source: "John Dee, 1564, Esoteric Archives",
    href: "https://www.esotericarchives.com/dee/monad.htm",
    license: "1564 treatise; English hosted there",
    implements: "The monas stage. A lecture object you can orbit. Not an instrument.",
  },
  {
    id: "agrippa",
    domain: "hermetica",
    title: "Three Books of Occult Philosophy",
    source: "Agrippa, 1533, Esoteric Archives",
    href: "https://www.esotericarchives.com/agrippa/agrippa1.htm",
    license: "Public-domain transcription",
    implements: "Renaissance natural philosophy. Read beside SEP, not instead of it.",
  },
  {
    id: "vscode",
    domain: "languages",
    title: "Visual Studio Code docs",
    source: "Microsoft",
    href: "https://code.visualstudio.com/docs",
    license: "Docs license on the site",
    implements: "One IDE. The desk is not an editor.",
  },
  {
    id: "neovim",
    domain: "languages",
    title: "Neovim documentation",
    source: "Neovim",
    href: "https://neovim.io/doc/",
    license: "Apache-2.0",
    implements: "Terminal editor named for the host, not embedded.",
  },
  {
    id: "gcc",
    domain: "languages",
    title: "GCC online docs",
    source: "GNU",
    href: "https://gcc.gnu.org/onlinedocs/",
    license: "GFDL",
    implements: "C and C++ authority. Noah's questions do not compile.",
  },
  {
    id: "llvm",
    domain: "languages",
    title: "LLVM documentation",
    source: "LLVM project",
    href: "https://llvm.org/docs/",
    license: "Apache-2.0 with exceptions",
    implements: "Compiler infrastructure reading for the systems path.",
  },
  {
    id: "ts",
    domain: "languages",
    title: "TypeScript handbook",
    source: "Microsoft",
    href: "https://www.typescriptlang.org/docs/",
    license: "Docs on the site",
    implements: "The language this app is written in.",
  },
  {
    id: "comptia",
    domain: "certifications",
    title: "CompTIA certifications",
    source: "CompTIA",
    href: "https://www.comptia.org/certifications",
    license: "Vendor",
    implements: "Official catalog only. No exam questions are stored here.",
  },
  {
    id: "aws-cert",
    domain: "certifications",
    title: "AWS Certification",
    source: "Amazon Web Services",
    href: "https://aws.amazon.com/certification/",
    license: "Vendor",
    implements: "The cloud paths point here. Practice is the studios, not a dump.",
  },
  {
    id: "cka",
    domain: "certifications",
    title: "CNCF Kubernetes certifications",
    source: "CNCF",
    href: "https://www.cncf.io/training/certification/",
    license: "Vendor",
    implements: "CKA exceed path. Objectives from the vendor, labs from us.",
  },
  {
    id: "rhcsa",
    domain: "certifications",
    title: "Red Hat Certified System Administrator",
    source: "Red Hat",
    href: "https://www.redhat.com/en/services/certification/rhcsa",
    license: "Vendor",
    implements: "Linux spine. The exam is taken on their systems, not ours.",
  },
  {
    id: "nvidia",
    domain: "certifications",
    title: "NVIDIA training",
    source: "NVIDIA",
    href: "https://www.nvidia.com/en-us/training/",
    license: "Vendor",
    implements: "The NVIDIA path. No GPU is attached to this preview.",
  },
  {
    id: "hashicorp-cert",
    domain: "certifications",
    title: "HashiCorp certifications",
    source: "HashiCorp",
    href: "https://developer.hashicorp.com/certifications",
    license: "Vendor",
    implements: "Terraform path. Official objectives, our own scenarios.",
  },
  {
    id: "lf-cert",
    domain: "certifications",
    title: "Linux Foundation certifications",
    source: "Linux Foundation",
    href: "https://www.linuxfoundation.org/certification",
    license: "Vendor",
    implements: "Essentials path. We do not reproduce their exam.",
  },
  {
    id: "domain",
    domain: "practice",
    title: "AI-aided cybersecurity domain",
    source: "Interstitium Labs",
    href: "/",
    license: "Original practice",
    implements: "Seventeen briefings, seven benches, one capstone. Reconstructed, not affiliated.",
  },
  {
    id: "paths",
    domain: "practice",
    title: "Path studios",
    source: "Interstitium Labs",
    href: "/paths",
    license: "Original practice",
    implements: "Each path has a reading, a motif stage, and a simulation whose bar tightens with load.",
  },
  {
    id: "noah",
    domain: "practice",
    title: "Noah",
    source: "Interstitium Labs",
    href: "/muse",
    license: "Original practice",
    implements: "The tutor. Question first. Mastery stays on this device.",
  },
  {
    id: "desk",
    domain: "practice",
    title: "Desk",
    source: "Interstitium Labs",
    href: "/desk",
    license: "Original practice",
    implements: "A parser for one permission change. Not a shell on the P920.",
  },
  {
    id: "radar",
    domain: "practice",
    title: "Radar",
    source: "Interstitium Labs",
    href: "/radar",
    license: "Original practice",
    implements: "What you have cleared, drawn as a field.",
  },
  {
    id: "mit-ocw",
    domain: "computing",
    title: "MIT OpenCourseWare",
    source: "MIT",
    href: "https://ocw.mit.edu/",
    license: "CC, per course",
    implements: "Open lectures. We link the shelf. We do not mirror the files.",
  },
  {
    id: "cmu-oli",
    domain: "computing",
    title: "Open Learning Initiative",
    source: "Carnegie Mellon",
    href: "https://oli.cmu.edu/",
    license: "OLI terms",
    implements: "Open courseware beside the ladders. Not imported as our quizzes.",
  },
  {
    id: "cs50",
    domain: "computing",
    title: "CS50",
    source: "Harvard",
    href: "https://cs50.harvard.edu/",
    license: "CC BY-NC-SA for much of the course",
    implements: "A public introduction. The desk here is still our parser, not their IDE.",
  },
  {
    id: "host",
    domain: "practice",
    title: "P920 host runbook",
    source: "Interstitium Labs",
    href: "/host",
    license: "Original practice",
    implements: "RHEL 10.2 on the ThinkStation, KVM, then a labs guest.",
  },
];

export type AtlasRoom = {
  room: string;
  was: string;
  now: string;
  href?: string;
  gap?: boolean;
};

export const atlas: AtlasRoom[] = [
  { room: "Academy, learn, paths", was: "Curriculum index", now: "Paths, with the cybersecurity domain folded in.", href: "/paths" },
  { room: "Adapt", was: "Load that changes the lesson", now: "The load slider on each path studio.", href: "/paths" },
  { room: "Coach, Noah", was: "Ask before the answer", now: "Noah at the desk, plus the fringe question. No due date.", href: "/muse" },
  { room: "Desk", was: "Working shell", now: "A permission parser. The real shell is on the host.", href: "/desk" },
  { room: "Radar, graph, measure", was: "Skill picture", now: "Radar.", href: "/radar" },
  { room: "Library, doctrine, code", was: "Sources and stack", now: "This canon, plus the stack page.", href: "/stack" },
  { room: "Labs, drill, exam, practice, prep, demo", was: "Benches and drills", now: "Briefings, benches, and the capstone. No exam-question bank.", href: "/lab/capstone" },
  { room: "Cinema, immersive, play", was: "3D and Unreal scaffold", now: "The motif stage. Unreal and Blender do not run in the page.", href: "/" },
  { room: "Plant, ops, platform, os, system", was: "How it is hosted", now: "The P920 runbook.", href: "/host" },
  { room: "Trending, frontier", was: "Outside signals", now: "Frontier path. A post is not a course until a path claims it.", href: "/paths/frontier" },
  { room: "Field, evidence, proof, portfolio", was: "Artifacts of work", now: "Field notes and progress on this device. No public portfolio backend." },
  { room: "Brand", was: "The sigil", now: "The same mark in the header and in every stage." },
  { room: "Enroll, pricing, admin, analytics", was: "Accounts and commerce", now: "Not built. Progress is local. There is no sign-in and no payment.", gap: true },
  { room: "i18n", was: "English and Spanish chrome", now: "English only in this build.", gap: true },
  { room: "Interview, factory, sheets, founders", was: "Hiring, production, sheets, about", now: "Not separate products. Hiring language stays inside the path readings.", gap: true },
];
